DROP TABLE IF EXISTS proizvod;

create table proizvod
(
    id    bigint generated by default as identity,
    naziv varchar(255),
    cena  double
--     primary key (id)
);

insert into proizvod (id, naziv, cena)
values (default,
        'Automobil',
        200);
insert into proizvod (id, naziv, cena)
values (default,
        'Knjiga',
        5000);